BU_URL = "https://www.bu.edu/academics/cas/courses"
MIT_URL = "https://student.mit.edu/catalog/index.cgi"
MAX_PAGES = 20
STOPWORDS = {"in", "and", "the", "of", "to", "a", "is", "with", "for"}
MIT_COURSE_PREFIXES = ['HST', 'MAS', 'SP', 'STS', 'SWE', 'TOX', 'TPP', 'ROTC', 'AS', 'MS', 'NS']
MIT_COURSE_DICT = { 'Civil and Environmental Engineering': '1',
                    'Mechanical Engineering': '2',
                    'Materials Science and Engineering': '3',
                    'Architecture': '4',
                    'Chemistry': '5',
                    'Electrical Engineering and Computer Science': '6',
                    'Biology': '7',
                    'Physics': '8',
                    'Brain and Cognitive Sciences': '9',
                    'Chemical Engineering': '10',
                    'Urban Studies and Planning': '11',
                    'Earth, Atmospheric, and Planetary Sciences': '12',
                    'Economics': '14',
                    'Management': '15',
                    'Aeronautics and Astronautics': '16',
                    'Political Science': '17',
                    'Mathematics': '18',
                    'Biological Engineering': '20',
                    'Humanities': '21',
                    'Anthropology': '21A',
                    'Comparative Media Studies': 'CMS',
                    'Writing': '21W',
                    'Global Languages': '21G',
                    'History': '21H',
                    'Literature': '21L',
                    'Music': '21M',
                    'Theater Arts': '21T',
                    "Women's and Gender Studies": 'WGS',
                    'Nuclear Science and Engineering': '22',
                    'Linguistics and Philosophy': '24',
                    'Concourse Program': 'CC',
                    'Common Ground for Computing Education': 'CG',
                    'Computational and Systems Biology': 'CSB',
                    'Center for Computational Science and Engineering': 'CSE',
                    'Edgerton Center': 'EC',
                    'Engineering Management': 'EM',
                    'Experimental Study Group': 'ES',
                    'Health Sciences and Technology': 'HST',
                    'Institute for Data, Systems and Society': 'IDS',
                    'Media Arts and Sciences': 'MAS',
                    'Supply Chain Management': 'SCM',
                    'Aerospace Studies': 'AS',
                    'Military Science': 'MS',
                    'Naval Science': 'NS',
                    'Science, Technology, and Society': 'STS',
                    'Engineering School': 'SWE',
                    'Special Programs': 'SP'}